describe('Form - testing our form inputs', function () {
    beforeEach(() => {
        cy.visit("http://localhost:3000/")
    })
    it("add text to inputs and submit form", function() {
        cy.get('[data-cy="name"]')
        .type("Jeremy")
        .should("have.value", "Jeremy")
        cy.get('[data-cy="email"]')
        .type("jChan@gmail.com")
        .should("have.value", "jChan@gmail.com")
        cy.get('[data-cy="motivation"]')
        .type("for reasons")
        .should("have.value", "for reasons")
        cy.get('[data-cy="positions"]')
        .select("Yard Work")
        .should("have.value", "Yard Work")
        cy.get('[data-cy="terms"]')
        .check()
        .should("be.checked")
        cy.get('[data-cy=submit]')
        .click()
    })
})